services:
  # app:
  #   image: duygusnmz/hello-app
  server:
    image: express-docker
    ports:
      - 5050:5000
  mongodb:
    image: mongo
  client:
    build: ./client
    ports:
      - 8080:3000
